# Generated by Django 6.0.2 on 2026-03-08 15:16

import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='auto_create_schema',
        ),
        migrations.RemoveField(
            model_name='school',
            name='auto_drop_schema',
        ),
        migrations.AlterField(
            model_name='school',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
