# Generated by Django 6.0.2 on 2026-03-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_school_auto_create_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='header_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='is_single_tenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='theme_color',
            field=models.CharField(blank=True, default='#4F46E5', max_length=20),
        ),
    ]
