# Generated by Django 6.0.2 on 2026-03-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_academicyear_unique_active_academic_year_per_school_and_more'),
        ('customers', '0004_subscription_plan_and_school_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Legacy - use plan instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='core.plan'),
        ),
    ]
