# Generated by Django 6.0.2 on 2026-03-19 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_saas_plan_and_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Trial, Basic, or Pro (legacy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='customers.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_per_student',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per student per month. Basic=39, Pro=59, Trial=0', max_digits=10),
        ),
    ]
