# Generated by Django 5.0.14 on 2026-03-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_schoolenrollmentrequest'),
        ('customers', '0011_platform_billing_engine'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='platforminvoice',
            name='saas_inv_year_month_idx',
        ),
        migrations.AddField(
            model_name='school',
            name='institution_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('INTERMEDIATE_COLLEGE', 'Intermediate College'), ('DEGREE_COLLEGE', 'Degree College'), ('PG_COLLEGE', 'PG College'), ('UNIVERSITY', 'University')], db_index=True, default='SCHOOL', help_text='Institution category (used for future workflow/label variations).', max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Trial / paid billing record (trial, basic, pro); pairs with Starter or Enterprise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='customers.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='school',
            name='saas_plan',
            field=models.ForeignKey(blank=True, help_text='Starter or Enterprise — controls which modules are available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='customers.plan'),
        ),
        migrations.AlterField(
            model_name='school',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Deprecated core.Plan link; use saas_plan (Starter/Enterprise)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='core.plan'),
        ),
    ]
