# Generated by Django 5.x migration stub

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0018_super_admin_v2_plan"),
        ("super_admin", "0003_plan_list_price_and_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolFeatureAddon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("extra_monthly_charge", models.DecimalField(decimal_places=2, default=0, help_text="Additional INR per month agreed for this feature (0 if bundled gratis).", max_digits=10)),
                ("notes", models.TextField(blank=True, help_text="Invoice ref, agreement, or internal note.")),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="school_feature_addons", to="super_admin.feature")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feature_addons", to="customers.school")),
            ],
            options={
                "ordering": ["school_id", "feature__category", "feature__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="schoolfeatureaddon",
            constraint=models.UniqueConstraint(fields=("school", "feature"), name="customers_schoolfeatureaddon_unique_school_feature"),
        ),
    ]
