# Generated by Django 6.0.2 on 2026-05-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_school_is_archived'),
        ('super_admin', '0006_tier_feature_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='plan',
            field=models.ForeignKey(blank=True, db_index=False, help_text='Basic / Pro / Premium — controls which modules are available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='super_admin.plan'),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='When false, this subscription row is ignored for feature access (paused or superseded).'),
        ),
    ]
