# Generated by Django 6.0.2 on 2026-03-08 15:16

import django.db.models.deletion
from django.db import migrations, models


def null_invalid_school_refs(apps, schema_editor):
    """Set school_id to NULL for users whose school code doesn't exist in customers_school."""
    if schema_editor.connection.schema_name != "public":
        return  # Only run on public schema
    with schema_editor.connection.cursor() as c:
        c.execute("""
            UPDATE accounts_user u
            SET school_id = NULL
            WHERE u.school_id IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 FROM customers_school s WHERE s.code = u.school_id
            )
        """)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_basic_plan_features'),
        ('customers', '0002_remove_school_auto_create_schema_and_more'),
    ]

    operations = [
        migrations.RunPython(null_invalid_school_refs, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='customers.school', to_field='code'),
        ),
    ]
