# Generated by Django 6.0.2 on 2026-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_blocked_login_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. Can be shared (e.g. parent email for multiple students).', max_length=254),
        ),
    ]
