# Generated by Django 6.0.2 on 2026-03-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0001_initial'),
        ('timetable', '0003_school_fk_to_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['order', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='school',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='school',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school_data.classroom'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='school_data.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='timetable_entries', to='school_data.teacher'),
        ),
    ]
