# Generated by Django 5.0.14 on 2026-03-30 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0028_badge_alter_exam_options_alter_examsession_options_and_more'),
        ('timetable', '0004_alter_timeslot_options_remove_timeslot_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='timetable.scheduleprofile'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.scheduleprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('classroom', 'profile', 'day_of_week', 'time_slot')},
        ),
    ]
