# Generated by Cursor on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0005_scheduleprofile_alter_timetable_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("TEACHING", "Teaching period"),
                    ("STUDY", "Study hours"),
                    ("READING", "Reading"),
                    ("GAMES", "Games"),
                    ("BREAK", "Break"),
                ],
                default="TEACHING",
                max_length=20,
            ),
        ),
    ]

