# Generated by Cursor on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0006_timeslot_slot_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="slot_label",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]

