# Generated by Django 6.0.2 on 2026-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_merge_scheduleprofile_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(choices=[('TEACHING', 'Teaching period'), ('STUDY', 'Study hours'), ('READING', 'Reading'), ('GAMES', 'Games'), ('PRACTICAL', 'Practical / Lab'), ('DOUBT', 'Doubt Clearing Session'), ('PROJECT', 'Project Work'), ('COMPUTER_LAB', 'Computer Lab'), ('OTHER', 'Other'), ('BREAK', 'Break')], default='TEACHING', max_length=20),
        ),
    ]
