"""
Create public.accounts_userprofile when migration 0008 has not been applied.

Use when `manage.py migrate` fails (e.g. django-tenants + inconsistent migration history)
but the profile page needs the table. Safe to run multiple times.

After fixing migration history, you can `migrate accounts 0008 --fake` if this command
already created the table and recorded the migration.
"""

from django.core.management.base import BaseCommand
from django.db import connection
from django.db.migrations.recorder import MigrationRecorder
from django.db.utils import ProgrammingError

# PostgreSQL DDL aligned with accounts.0008_user_profile (+ timestamp defaults for inserts)
_PG_CREATE = '''
CREATE TABLE IF NOT EXISTS "accounts_userprofile" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "avatar" varchar(100) NULL,
    "middle_name" varchar(150) NOT NULL,
    "display_name" varchar(255) NOT NULL,
    "date_of_birth" date NULL,
    "gender" varchar(1) NOT NULL,
    "marital_status" varchar(20) NOT NULL,
    "blood_group" varchar(4) NOT NULL,
    "nationality" varchar(120) NOT NULL,
    "aadhaar_or_govt_id" varchar(32) NOT NULL,
    "emergency_contact_name" varchar(255) NOT NULL,
    "emergency_contact_phone" varchar(32) NOT NULL,
    "secondary_email" varchar(254) NOT NULL,
    "alternate_phone" varchar(32) NOT NULL,
    "whatsapp_number" varchar(32) NOT NULL,
    "address_line1" varchar(255) NOT NULL,
    "address_line2" varchar(255) NOT NULL,
    "city" varchar(120) NOT NULL,
    "state" varchar(120) NOT NULL,
    "pin_code" varchar(16) NOT NULL,
    "country" varchar(120) NOT NULL,
    "department" varchar(120) NOT NULL,
    "designation" varchar(120) NOT NULL,
    "branch" varchar(120) NOT NULL,
    "employee_code" varchar(64) NOT NULL,
    "official_email" varchar(254) NOT NULL,
    "language" varchar(32) NOT NULL,
    "timezone" varchar(64) NOT NULL,
    "theme" varchar(16) NOT NULL,
    "notify_in_app" boolean NOT NULL,
    "notify_email" boolean NOT NULL,
    "notify_sms" boolean NOT NULL,
    "two_factor_enabled" boolean NOT NULL,
    "password_changed_at" timestamp with time zone NULL,
    "profile_updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "profile_updated_by_id" bigint NULL,
    "reporting_manager_id" bigint NULL,
    "user_id" bigint NOT NULL UNIQUE
);
'''

_PG_FKS = [
    '''ALTER TABLE "accounts_userprofile" ADD CONSTRAINT "accounts_userprofile_profile_updated_by_i_97ce093b_fk_accounts_"
        FOREIGN KEY ("profile_updated_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED''',
    '''ALTER TABLE "accounts_userprofile" ADD CONSTRAINT "accounts_userprofile_reporting_manager_id_6a05583d_fk_accounts_"
        FOREIGN KEY ("reporting_manager_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED''',
    '''ALTER TABLE "accounts_userprofile" ADD CONSTRAINT "accounts_userprofile_user_id_92240672_fk_accounts_user_id"
        FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED''',
]

_PG_INDEXES = [
    'CREATE INDEX IF NOT EXISTS "accounts_userprofile_profile_updated_by_id_97ce093b" ON "accounts_userprofile" ("profile_updated_by_id");',
    'CREATE INDEX IF NOT EXISTS "accounts_userprofile_reporting_manager_id_6a05583d" ON "accounts_userprofile" ("reporting_manager_id");',
]


def _table_exists(cursor, name: str) -> bool:
    cursor.execute(
        """
        SELECT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = current_schema() AND table_name = %s
        );
        """,
        [name],
    )
    return bool(cursor.fetchone()[0])


def _record_migration() -> None:
    recorder = MigrationRecorder(connection)
    key = ("accounts", "0008_user_profile")
    if key in recorder.applied_migrations():
        return
    recorder.record_applied(*key)


class Command(BaseCommand):
    help = "Creates accounts_userprofile table and rows if missing (PostgreSQL public schema)."

    def handle(self, *args, **options):
        if connection.vendor != "postgresql":
            self.stderr.write(
                self.style.ERROR(
                    "This command only supports PostgreSQL. Run migrations when your DB is fixed: "
                    "python manage.py migrate_schemas --shared"
                )
            )
            return

        with connection.cursor() as cursor:
            if _table_exists(cursor, "accounts_userprofile"):
                self.stdout.write(self.style.SUCCESS("accounts_userprofile already exists."))
                self._backfill()
                _record_migration()
                return

            self.stdout.write("Creating accounts_userprofile …")
            cursor.execute(_PG_CREATE)

            for stmt in _PG_FKS:
                try:
                    cursor.execute(stmt)
                except ProgrammingError as e:
                    if "already exists" not in str(e).lower():
                        raise

            for stmt in _PG_INDEXES:
                cursor.execute(stmt)

        self._backfill()
        _record_migration()
        self.stdout.write(
            self.style.SUCCESS(
                "Done. Profile page should load. If you later repair migration history, "
                "you may use: python manage.py migrate accounts 0008_user_profile --fake"
            )
        )

    def _backfill(self) -> None:
        from apps.accounts.models import User, UserProfile

        created = 0
        batch_size = 500
        last_pk = None
        while True:
            q = User.objects.order_by("pk")
            if last_pk is not None:
                q = q.filter(pk__gt=last_pk)
            batch = list(q[:batch_size])
            if not batch:
                break
            for user in batch:
                _, was_created = UserProfile.objects.get_or_create(user=user)
                if was_created:
                    created += 1
            last_pk = batch[-1].pk
        if created:
            self.stdout.write(self.style.NOTICE(f"Created {created} user profile row(s)."))
