# Generated by Django 6.0.2 on 2026-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0006_remove_section_classroom_and_cleanup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section_name',
        ),
        # DB already has no unique_together (classroom,name) - dropped with column in 0006.
        # Update state only so future migrations see correct model.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='section',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
