# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_data", "0008_add_test_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, only this teacher sees the exam. Admin sees all.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_exams",
                to="school_data.teacher",
            ),
        ),
    ]
