# Generated by Django 5.0.14 on 2026-03-30 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0027_payment_transaction_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='bi bi-star-fill', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'exam paper', 'verbose_name_plural': 'exam papers'},
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'exam session', 'verbose_name_plural': 'exam sessions'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_date',
        ),
        migrations.AddField(
            model_name='exam',
            name='class_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Legacy denormalized classroom name (kept for backward compatibility).', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Legacy denormalized section name (kept for backward compatibility).', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Optional. When set, this teacher is assigned to the exam.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to='school_data.teacher'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='class_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Legacy denormalized classroom name (kept for backward compatibility).', max_length=50),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='section',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Legacy denormalized section name (kept for backward compatibility).', max_length=10),
        ),
        migrations.AlterField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_homework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='InternalChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(db_index=True)),
                ('user_low_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('user_high_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_chat_threads_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_chat_threads_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('user_low', 'user_high')},
            },
        ),
        migrations.CreateModel(
            name='InternalChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school_data.internalchatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_students', to='school_data.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='school_data.student')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddConstraint(
            model_name='studentbadge',
            constraint=models.UniqueConstraint(fields=('student', 'badge'), name='unique_student_badge'),
        ),
    ]
