# Generated by Django 5.0.14 on 2026-03-30 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0028_badge_alter_exam_options_alter_examsession_options_and_more'),
        ('timetable', '0005_scheduleprofile_alter_timetable_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='active_schedule_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_classrooms', to='timetable.scheduleprofile'),
        ),
    ]
