# Generated by GPT-5.2 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_data", "0074_teacherclasssection"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("seen", "Seen"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="sent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentmessage",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentmessage",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

