# Generated by Django 6.0.2 on 2026-05-07 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0075_studentmessage_status_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['academic_year', 'grade_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['fee_type', 'classroom__grade_order', 'classroom__name']},
        ),
        migrations.AlterModelOptions(
            name='masterdataoption',
            options={'ordering': ['key', 'display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RenameField(
            model_name='dropdownmaster',
            old_name='updated_on',
            new_name='modified_on',
        ),
        migrations.RemoveField(
            model_name='dropdownmaster',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='dropdownmaster',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admission_number',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Auto generated like 26chs_2536486vc', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admission',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionstatushistory',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionstatushistory',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dropdownmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dropdownmaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='holidayevent',
            name='end_date',
            field=models.DateField(db_index=True, help_text='Must match holiday date; kept for schema compatibility.'),
        ),
        migrations.AlterField(
            model_name='holidayevent',
            name='recurring_yearly',
            field=models.BooleanField(default=False, help_text='If set, this holiday repeats on the same month/day each year within the academic year.'),
        ),
        migrations.AlterField(
            model_name='holidayevent',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Holiday date'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='assigned_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date the work was given (defaults to today on create if left blank).', null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Rough effort estimate for students and parents.', null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='How to submit, materials, format — separate from task description.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='max_marks',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional cap for internal grading.', null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_required',
            field=models.BooleanField(default=True, help_text='If off, students see the task but no file upload is expected.'),
        ),
        migrations.AlterField(
            model_name='masterdataoption',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterdataoption',
            name='key',
            field=models.CharField(choices=[('gender', 'Gender'), ('blood_group', 'Blood group'), ('nationality', 'Nationality'), ('religion', 'Religion'), ('mother_tongue', 'Mother tongue'), ('designation', 'Designation'), ('department', 'Department'), ('qualification', 'Qualification'), ('caste_category', 'Caste / Category'), ('marital_status', 'Marital status'), ('staff_type', 'Staff type'), ('employment_type', 'Employment type'), ('shift', 'Shift'), ('payroll_category', 'Payroll category'), ('experience_level', 'Experience level'), ('reporting_manager', 'Reporting manager'), ('relationship', 'Relationship'), ('occupation', 'Occupation'), ('annual_income_range', 'Annual income range'), ('education_level', 'Education level'), ('admission_source', 'Admission source'), ('fee_category', 'Fee category'), ('student_status', 'Student status'), ('previous_board', 'Previous board'), ('medium_of_instruction', 'Medium of instruction'), ('attendance_status', 'Attendance status'), ('admission_status', 'Admission status'), ('transport_required', 'Transport required'), ('status', 'Status')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='masterdataoption',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
