# Generated by Django 6.0.2 on 2026-03-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teacher_qualification_user_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['start_date']},
        ),
    ]
