# Generated by Django 6.0.2 on 2026-03-08 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_school_from_user(apps, schema_editor):
    """Populate Student.school and Teacher.school from user.school for existing records."""
    Student = apps.get_model("core", "Student")
    Teacher = apps.get_model("core", "Teacher")
    for s in Student.objects.select_related("user"):
        if s.user_id and s.user.school_id:
            s.school_id = s.user.school_id
            s.save(update_fields=["school_id"])
    for t in Teacher.objects.select_related("user"):
        if t.user_id and t.user.school_id:
            t.school_id = t.user.school_id
            t.save(update_fields=["school_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_school_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school', to_field='code'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.school', to_field='code'),
        ),
        migrations.RunPython(populate_school_from_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='academicyear',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('admission_number__gt', ''), ('school__isnull', False)), fields=('school', 'admission_number'), name='unique_admission_per_school'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id__gt', ''), ('school__isnull', False)), fields=('school', 'employee_id'), name='unique_employee_id_per_school'),
        ),
    ]
