# Generated by Django 6.0.2 on 2026-03-08 15:16
# Simplified: core tenant models (ClassRoom, Student, etc.) live in school_data and
# tenant schemas. This migration originally removed them from core in public schema;
# those tables/constraints do not exist in public, so we no-op to advance migration state.

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_school'),
        ('core', '0015_add_subscription_plan_models'),
        ('timetable', '0004_alter_timeslot_options_remove_timeslot_school_and_more'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
