# Generated by Django 6.0.2 on 2026-05-07 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_schoolenrollmentrequest_optional_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sidebarmenuitem',
            new_name='core_sideba_role_15dbec_idx',
            old_name='core_sideb_role_9b6a49_idx',
        ),
        migrations.AlterField(
            model_name='analyticsfield',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyticsfield',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolenrollmentrequest',
            name='intended_plan',
            field=models.CharField(blank=True, help_text='trial, basic, standard, enterprise, yearly — post-trial billing preference (audit).', max_length=32),
        ),
        migrations.AlterField(
            model_name='schoolenrollmentrequest',
            name='society_name',
            field=models.CharField(blank=True, default='', help_text='Housing society, trust, or registered name (as on society / RWA records).', max_length=255),
        ),
        migrations.AlterField(
            model_name='sidebarmenuitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sidebarmenuitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
