"""
Create core_schoolenrollmentrequest on the public schema when migrate is blocked
(InconsistentMigrationHistory). Safe to re-run.

Run: python manage.py ensure_school_enrollment_table
"""
from django.core.management.base import BaseCommand
from django.db import connection
from django_tenants.utils import get_public_schema_name


MIGRATION_NAME = "0019_schoolenrollmentrequest"


class Command(BaseCommand):
    help = "Ensure public table core_schoolenrollmentrequest exists (enroll form)."

    def handle(self, *args, **options):
        public = get_public_schema_name()
        connection.set_schema_to_public()

        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = %s AND table_name = 'core_schoolenrollmentrequest';
                """,
                [public],
            )
            if cursor.fetchone():
                self.stdout.write(self.style.SUCCESS("Table core_schoolenrollmentrequest already exists."))
            else:
                self.stdout.write("Creating core_schoolenrollmentrequest...")
                # Matches sqlmigrate core 0019_schoolenrollmentrequest (PostgreSQL)
                cursor.execute(
                    """
                    CREATE TABLE "core_schoolenrollmentrequest" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "institution_name" varchar(255) NOT NULL,
                        "contact_name" varchar(255) NOT NULL,
                        "email" varchar(254) NOT NULL,
                        "phone" varchar(30) NOT NULL,
                        "notes" text NOT NULL,
                        "status" varchar(20) NOT NULL,
                        "provisioned_schema_name" varchar(63) NOT NULL,
                        "reviewed_at" timestamp with time zone NULL,
                        "decline_reason" text NOT NULL,
                        "created_at" timestamp with time zone NOT NULL,
                        "reviewed_by_id" bigint NULL,
                        "school_id" bigint NULL
                    );
                    """
                )
                cursor.execute(
                    """
                    ALTER TABLE "core_schoolenrollmentrequest"
                    ADD CONSTRAINT "core_schoolenrollmen_reviewed_by_id_2d008d3e_fk_accounts_"
                    FOREIGN KEY ("reviewed_by_id") REFERENCES "accounts_user" ("id")
                    DEFERRABLE INITIALLY DEFERRED;
                    """
                )
                cursor.execute(
                    """
                    ALTER TABLE "core_schoolenrollmentrequest"
                    ADD CONSTRAINT "core_schoolenrollmen_school_id_b8622539_fk_customers"
                    FOREIGN KEY ("school_id") REFERENCES "customers_school" ("id")
                    DEFERRABLE INITIALLY DEFERRED;
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "core_schoolenrollmentrequest_status_b6278a67"
                    ON "core_schoolenrollmentrequest" ("status");
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "core_schoolenrollmentrequest_status_b6278a67_like"
                    ON "core_schoolenrollmentrequest" ("status" varchar_pattern_ops);
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "core_schoolenrollmentrequest_reviewed_by_id_2d008d3e"
                    ON "core_schoolenrollmentrequest" ("reviewed_by_id");
                    """
                )
                cursor.execute(
                    """
                    CREATE INDEX "core_schoolenrollmentrequest_school_id_b8622539"
                    ON "core_schoolenrollmentrequest" ("school_id");
                    """
                )
                self.stdout.write(self.style.SUCCESS("Created table."))

            cursor.execute(
                """
                SELECT 1 FROM django_migrations
                WHERE app = 'core' AND name = %s;
                """,
                [MIGRATION_NAME],
            )
            if cursor.fetchone():
                self.stdout.write(f"Migration core.{MIGRATION_NAME} already recorded.")
            else:
                cursor.execute(
                    """
                    INSERT INTO django_migrations (app, name, applied)
                    VALUES ('core', %s, NOW());
                    """,
                    [MIGRATION_NAME],
                )
                self.stdout.write(self.style.SUCCESS(f"Recorded core.{MIGRATION_NAME} in django_migrations."))

        self.stdout.write(self.style.SUCCESS("Done. /enroll/ should work now."))
