from django.urls import path

from apps.platform_messaging import api as platform_messages_api
from apps.platform_messaging import views_pages as platform_messages_pages

from . import analytics_api, control_center_settings_api, views

app_name = "super_admin"

urlpatterns = [
    path("control-center/", views.control_center_root, name="control_center"),
    path(
        "control-center/schools/create/",
        views.control_center_school_create,
        name="control_center_school_create",
    ),
    path(
        "control-center/schools/<int:school_id>/",
        views.school_master_detail,
        name="school_master_detail",
    ),
    path(
        "control-center/billing/<int:school_id>/",
        views.billing_school_detail,
        name="billing_school_detail",
    ),
    path(
        "control-center/billing/<int:school_id>/invoice/<int:invoice_id>/receive/",
        views.billing_school_receive_payment,
        name="billing_school_receive_payment",
    ),
    path(
        "control-center/api/analytics/summary/",
        analytics_api.analytics_summary_api,
        name="analytics_summary",
    ),
    path(
        "control-center/api/analytics/revenue-trend/",
        analytics_api.analytics_revenue_trend_api,
        name="analytics_revenue_trend",
    ),
    path(
        "control-center/api/analytics/school-revenue/",
        analytics_api.analytics_school_revenue_api,
        name="analytics_school_revenue",
    ),
    path(
        "control-center/api/analytics/payment-status/",
        analytics_api.analytics_payment_status_api,
        name="analytics_payment_status",
    ),
    path(
        "control-center/api/analytics/growth/",
        analytics_api.analytics_growth_api,
        name="analytics_growth",
    ),
    path(
        "control-center/api/analytics/month-collection/",
        analytics_api.analytics_month_collection_api,
        name="analytics_month_collection",
    ),
    path(
        "control-center/api/analytics/plan-distribution/",
        analytics_api.analytics_plan_distribution_api,
        name="analytics_plan_distribution",
    ),
    path(
        "control-center/api/analytics/top-risk/",
        analytics_api.analytics_top_and_risk_api,
        name="analytics_top_risk",
    ),
    path(
        "control-center/api/analytics/export.csv",
        analytics_api.analytics_export_csv,
        name="analytics_export_csv",
    ),
    path(
        "control-center/api/settings/",
        control_center_settings_api.control_center_settings_get_api,
        name="control_center_settings_get",
    ),
    path(
        "control-center/api/settings/update/",
        control_center_settings_api.control_center_settings_update_api,
        name="control_center_settings_update",
    ),
    path(
        "control-center/api/settings/reset/",
        control_center_settings_api.control_center_settings_reset_api,
        name="control_center_settings_reset",
    ),
    path(
        "control-center/messages/",
        platform_messages_pages.superadmin_messages_page,
        name="platform_messages",
    ),
    path(
        "control-center/messages/api/threads/",
        platform_messages_api.sa_threads,
        name="platform_messages_api_threads",
    ),
    path(
        "control-center/messages/api/school/<int:school_id>/messages/",
        platform_messages_api.sa_messages,
        name="platform_messages_api_messages",
    ),
    path(
        "control-center/messages/api/send/",
        platform_messages_api.sa_send,
        name="platform_messages_api_send",
    ),
    path(
        "control-center/messages/api/mark-read/",
        platform_messages_api.sa_mark_read,
        name="platform_messages_api_mark_read",
    ),
    path(
        "control-center/messages/api/thread-state/",
        platform_messages_api.sa_thread_state,
        name="platform_messages_api_thread_state",
    ),
    path(
        "control-center/messages/api/broadcast/",
        platform_messages_api.sa_broadcast,
        name="platform_messages_api_broadcast",
    ),
    path("control-center/<str:section>/", views.control_center, name="control_center_section"),
    path(
        "control-center/api/schools/update-billing-config/",
        views.schools_update_billing_config_api,
        name="schools_api_update_billing_config",
    ),
    path(
        "control-center/api/schools/",
        views.schools_billing_config_list_api,
        name="schools_api_list",
    ),
    path(
        "control-center/api/billing-school/<int:school_id>/",
        views.billing_school_update_api,
        name="billing_school_api",
    ),
    path(
        "control-center/api/billing-school/<int:school_id>/details/",
        views.billing_school_details_api,
        name="billing_school_details",
    ),
    path(
        "control-center/api/billing-school/<int:school_id>/action/",
        views.billing_school_action_api,
        name="billing_school_action",
    ),
    # REST-style SaaS billing API (full URL prefix: /super-admin/control-center/api/billing/…)
    path(
        "control-center/api/billing/schools/",
        views.billing_schools_list_api,
        name="billing_api_schools",
    ),
    path(
        "control-center/api/billing/update-extra/",
        views.billing_api_update_extra,
        name="billing_api_update_extra",
    ),
    path(
        "control-center/api/billing/update-concession/",
        views.billing_api_update_concession,
        name="billing_api_update_concession",
    ),
    path(
        "control-center/api/billing/update-plan/",
        views.billing_api_update_plan,
        name="billing_api_update_plan",
    ),
    path(
        "control-center/api/billing/update-students/",
        views.billing_api_update_students,
        name="billing_api_update_students",
    ),
    path(
        "control-center/api/billing/generate-invoice/",
        views.billing_api_generate_invoice,
        name="billing_api_generate_invoice",
    ),
    path(
        "control-center/api/billing/invoices/",
        views.billing_api_invoices_list,
        name="billing_api_invoices_list",
    ),
    path(
        "control-center/api/billing/mark-paid/",
        views.billing_api_mark_paid,
        name="billing_api_mark_paid",
    ),
    path(
        "control-center/api/billing/update-invoice-period/",
        views.billing_api_update_invoice_period,
        name="billing_api_update_invoice_period",
    ),
    path(
        "control-center/api/billing/export.csv",
        views.billing_export_csv,
        name="billing_export_csv",
    ),
    path(
        "control-center/api/billing/send-reminder/",
        views.billing_send_payment_reminder_api,
        name="billing_api_send_reminder",
    ),
    path(
        "control-center/api/billing/coupons/",
        views.billing_coupons_list_api,
        name="billing_api_coupons",
    ),
]

