"""
Apply customers 0008 schema changes when `migrate` is blocked (e.g. inconsistent
django_migrations history). Safe to run multiple times (PostgreSQL / public schema).

After this, `/school/dashboard/` and other code using School.contact_person work.

Optional: align migration history so future `migrate` works:
  python manage.py ensure_customers_billing_schema --record-migration
"""
from django.core.management.base import BaseCommand
from django.db import connection
def _pg_exec(cursor, sql: str) -> None:
    cursor.execute(sql)


class Command(BaseCommand):
    help = "Idempotently add Plan/School billing columns and Coupon / SchoolSubscription tables (customers 0008)."

    def add_arguments(self, parser):
        parser.add_argument(
            "--record-migration",
            action="store_true",
            help="Insert django_migrations rows for 0007 (if missing) and 0008 so migrate stops re-applying.",
        )

    def handle(self, *args, **options):
        if connection.vendor != "postgresql":
            self.stderr.write(self.style.ERROR("This command only supports PostgreSQL (django-tenants backend)."))
            return

        with connection.cursor() as cursor:
            _pg_exec(
                cursor,
                """
                DO $ensure$
                BEGIN
                  IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'customers_plan' AND column_name = 'billing_cycle'
                  ) THEN
                    ALTER TABLE customers_plan ADD COLUMN billing_cycle varchar(20) DEFAULT 'monthly' NOT NULL;
                    ALTER TABLE customers_plan ALTER COLUMN billing_cycle DROP DEFAULT;
                  END IF;
                  IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'customers_plan' AND column_name = 'is_active'
                  ) THEN
                    ALTER TABLE customers_plan ADD COLUMN is_active boolean DEFAULT true NOT NULL;
                    ALTER TABLE customers_plan ALTER COLUMN is_active DROP DEFAULT;
                  END IF;
                  IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'customers_school' AND column_name = 'contact_person'
                  ) THEN
                    ALTER TABLE customers_school ADD COLUMN contact_person varchar(200) DEFAULT '' NOT NULL;
                    ALTER TABLE customers_school ALTER COLUMN contact_person DROP DEFAULT;
                  END IF;
                  IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = 'customers_school' AND column_name = 'school_status'
                  ) THEN
                    ALTER TABLE customers_school ADD COLUMN school_status varchar(20) DEFAULT 'active' NOT NULL;
                    ALTER TABLE customers_school ALTER COLUMN school_status DROP DEFAULT;
                  END IF;
                END
                $ensure$;
                """,
            )
            self.stdout.write(self.style.SUCCESS("Plan + School columns OK."))

            cursor.execute(
                """
                SELECT EXISTS (
                  SELECT 1 FROM information_schema.tables
                  WHERE table_schema = 'public' AND table_name = 'customers_coupon'
                )
                """
            )
            if not cursor.fetchone()[0]:
                _pg_exec(
                    cursor,
                    """
                    CREATE TABLE customers_coupon (
                      id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      code varchar(40) NOT NULL UNIQUE,
                      discount_type varchar(20) NOT NULL,
                      discount_value numeric(10, 2) NOT NULL,
                      max_usage integer NOT NULL CHECK (max_usage >= 0),
                      used_count integer NOT NULL CHECK (used_count >= 0),
                      valid_from date NULL,
                      valid_to date NULL,
                      is_active boolean NOT NULL DEFAULT true,
                      created_at timestamp with time zone NOT NULL DEFAULT now()
                    );
                    """,
                )
                self.stdout.write(self.style.SUCCESS("Created customers_coupon."))
            else:
                self.stdout.write("customers_coupon already exists.")

            cursor.execute(
                """
                SELECT EXISTS (
                  SELECT 1 FROM information_schema.tables
                  WHERE table_schema = 'public' AND table_name = 'customers_schoolsubscription'
                )
                """
            )
            if not cursor.fetchone()[0]:
                _pg_exec(
                    cursor,
                    """
                    CREATE TABLE customers_schoolsubscription (
                      id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      start_date date NOT NULL,
                      end_date date NULL,
                      students_count integer NOT NULL CHECK (students_count >= 0),
                      free_months_applied smallint NOT NULL CHECK (free_months_applied >= 0),
                      status varchar(20) NOT NULL,
                      is_current boolean NOT NULL,
                      created_at timestamp with time zone NOT NULL DEFAULT now(),
                      updated_at timestamp with time zone NOT NULL DEFAULT now(),
                      coupon_id bigint NULL,
                      plan_id bigint NOT NULL,
                      school_id bigint NOT NULL
                    );
                    ALTER TABLE customers_schoolsubscription
                      ADD CONSTRAINT customers_schoolsubs_coupon_id_fk
                      FOREIGN KEY (coupon_id) REFERENCES customers_coupon (id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE customers_schoolsubscription
                      ADD CONSTRAINT customers_schoolsubs_plan_id_fk
                      FOREIGN KEY (plan_id) REFERENCES customers_plan (id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE customers_schoolsubscription
                      ADD CONSTRAINT customers_schoolsubs_school_id_fk
                      FOREIGN KEY (school_id) REFERENCES customers_school (id) DEFERRABLE INITIALLY DEFERRED;
                    CREATE UNIQUE INDEX customers_schoolsub_unique_current_school
                      ON customers_schoolsubscription (school_id) WHERE is_current;
                    CREATE INDEX customers_schoolsubscription_status ON customers_schoolsubscription (status);
                    CREATE INDEX customers_schoolsubscription_is_current ON customers_schoolsubscription (is_current);
                    CREATE INDEX customers_schoolsubscription_coupon_id ON customers_schoolsubscription (coupon_id);
                    CREATE INDEX customers_schoolsubscription_plan_id ON customers_schoolsubscription (plan_id);
                    CREATE INDEX customers_schoolsubscription_school_id ON customers_schoolsubscription (school_id);
                    """,
                )
                self.stdout.write(self.style.SUCCESS("Created customers_schoolsubscription."))
            else:
                self.stdout.write("customers_schoolsubscription already exists.")

            # Indexes (ignore if exist)
            for stmt in (
                'CREATE INDEX IF NOT EXISTS customers_plan_billing_cycle_idx ON customers_plan (billing_cycle);',
                'CREATE INDEX IF NOT EXISTS customers_plan_is_active_idx ON customers_plan (is_active);',
                'CREATE INDEX IF NOT EXISTS customers_school_school_status_idx ON customers_school (school_status);',
                'CREATE INDEX IF NOT EXISTS customers_coupon_is_active_idx ON customers_coupon (is_active);',
            ):
                cursor.execute(stmt)

            cursor.execute(
                """
                SELECT EXISTS (
                  SELECT 1 FROM information_schema.tables
                  WHERE table_schema = 'public' AND table_name = 'customers_saasplatformpayment'
                )
                """
            )
            if not cursor.fetchone()[0]:
                _pg_exec(
                    cursor,
                    """
                    CREATE TABLE customers_saasplatformpayment (
                      id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      amount numeric(12, 2) NOT NULL,
                      payment_date date NOT NULL,
                      payment_method varchar(30) NOT NULL,
                      reference varchar(200) NOT NULL DEFAULT '',
                      notes text NOT NULL DEFAULT '',
                      created_at timestamp with time zone NOT NULL DEFAULT now(),
                      recorded_by_id bigint NULL,
                      school_id bigint NOT NULL,
                      subscription_id bigint NULL,
                      CONSTRAINT saaspay_school_fk FOREIGN KEY (school_id)
                        REFERENCES customers_school (id) DEFERRABLE INITIALLY DEFERRED,
                      CONSTRAINT saaspay_sub_fk FOREIGN KEY (subscription_id)
                        REFERENCES customers_schoolsubscription (id) DEFERRABLE INITIALLY DEFERRED,
                      CONSTRAINT saaspay_user_fk FOREIGN KEY (recorded_by_id)
                        REFERENCES accounts_user (id) DEFERRABLE INITIALLY DEFERRED
                    );
                    CREATE INDEX customers_saasplatformpayment_paydate
                      ON customers_saasplatformpayment (payment_date);
                    CREATE INDEX customers_saasplatformpayment_school
                      ON customers_saasplatformpayment (school_id);
                    """,
                )
                self.stdout.write(self.style.SUCCESS("Created customers_saasplatformpayment."))
            else:
                self.stdout.write("customers_saasplatformpayment already exists.")

        if options["record_migration"]:
            from django.db.migrations.recorder import MigrationRecorder

            recorder = MigrationRecorder(connection)
            for app, name in (
                ("customers", "0007_alter_school_plan_and_more"),
                ("customers", "0008_billing_plans_coupons_subscriptions"),
                ("customers", "0009_saas_platform_payment"),
            ):
                if not recorder.migration_qs.filter(app=app, name=name).exists():
                    recorder.record_applied(app, name)
                    self.stdout.write(self.style.SUCCESS(f"Recorded migration {app}.{name}"))
                else:
                    self.stdout.write(f"Migration already recorded: {app}.{name}")

        self.stdout.write(
            self.style.NOTICE(
                "Done. Reload /school/dashboard/. If migrate still errors, fix django_migrations order "
                "or use --record-migration only when DB matches those migrations."
            )
        )
