"""
Idempotent public-schema DDL for SchoolEnrollmentRequest when migrations are blocked or incomplete.
Used by /enroll/ and by ensure_school_enrollment_table management command.
"""
from __future__ import annotations

import logging

from django.db import connection

logger = logging.getLogger(__name__)

TABLE = "core_schoolenrollmentrequest"


def _public_schema_name() -> str:
    try:
        from django_tenants.utils import get_public_schema_name

        return get_public_schema_name()
    except Exception:
        return "public"


def _is_postgres() -> bool:
    engine = connection.settings_dict.get("ENGINE") or ""
    return "postgresql" in engine


def _table_exists(cursor, schema: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = %s AND table_name = %s
        """,
        [schema, TABLE],
    )
    return cursor.fetchone() is not None


def _existing_columns(cursor, schema: str) -> set[str]:
    cursor.execute(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = %s AND table_name = %s
        """,
        [schema, TABLE],
    )
    return {row[0] for row in cursor.fetchall()}


def _create_table_and_constraints(cursor) -> None:
    """Full table matching SchoolEnrollmentRequest after core 0019 + 0020."""
    cursor.execute(
        f'''
        CREATE TABLE "{TABLE}" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "institution_name" varchar(255) NOT NULL,
            "institution_code" varchar(100) NOT NULL,
            "contact_name" varchar(255) NOT NULL,
            "email" varchar(254) NOT NULL,
            "phone" varchar(30) NOT NULL,
            "address" text NOT NULL,
            "city" varchar(120) NOT NULL,
            "state" varchar(120) NOT NULL,
            "pincode" varchar(20) NOT NULL,
            "student_count" integer NULL,
            "teacher_count" integer NULL,
            "branch_count" integer NULL,
            "preferred_username" varchar(150) NOT NULL,
            "pending_password_hash" varchar(128) NOT NULL,
            "intended_plan" varchar(32) NOT NULL,
            "notes" text NOT NULL,
            "status" varchar(20) NOT NULL,
            "provisioned_schema_name" varchar(63) NOT NULL,
            "reviewed_at" timestamp with time zone NULL,
            "decline_reason" text NOT NULL,
            "created_at" timestamp with time zone NOT NULL,
            "reviewed_by_id" bigint NULL,
            "school_id" bigint NULL
        );
        '''
    )
    cursor.execute(
        f'''
        ALTER TABLE "{TABLE}"
        ADD CONSTRAINT "core_schoolenrollmen_reviewed_by_id_2d008d3e_fk_accounts_"
        FOREIGN KEY ("reviewed_by_id") REFERENCES "accounts_user" ("id")
        DEFERRABLE INITIALLY DEFERRED;
        '''
    )
    cursor.execute(
        f'''
        ALTER TABLE "{TABLE}"
        ADD CONSTRAINT "core_schoolenrollmen_school_id_b8622539_fk_customers"
        FOREIGN KEY ("school_id") REFERENCES "customers_school" ("id")
        DEFERRABLE INITIALLY DEFERRED;
        '''
    )
    for stmt in (
        f'CREATE INDEX "core_schoolenrollmentrequest_status_b6278a67" ON "{TABLE}" ("status");',
        f'CREATE INDEX "core_schoolenrollmentrequest_status_b6278a67_like" ON "{TABLE}" ("status" varchar_pattern_ops);',
        f'CREATE INDEX "core_schoolenrollmentrequest_reviewed_by_id_2d008d3e" ON "{TABLE}" ("reviewed_by_id");',
        f'CREATE INDEX "core_schoolenrollmentrequest_school_id_b8622539" ON "{TABLE}" ("school_id");',
    ):
        cursor.execute(stmt)


# (column_name, ADD COLUMN ... fragment after ADD COLUMN keyword)
_EXTRA_COLUMNS = [
    ("institution_code", '"institution_code" varchar(100) NOT NULL DEFAULT \'\''),
    ("address", '"address" text NOT NULL DEFAULT \'\''),
    ("city", '"city" varchar(120) NOT NULL DEFAULT \'\''),
    ("state", '"state" varchar(120) NOT NULL DEFAULT \'\''),
    ("pincode", '"pincode" varchar(20) NOT NULL DEFAULT \'\''),
    ("student_count", '"student_count" integer NULL'),
    ("teacher_count", '"teacher_count" integer NULL'),
    ("branch_count", '"branch_count" integer NULL'),
    ("preferred_username", '"preferred_username" varchar(150) NOT NULL DEFAULT \'\''),
    ("pending_password_hash", '"pending_password_hash" varchar(128) NOT NULL DEFAULT \'\''),
    ("intended_plan", '"intended_plan" varchar(32) NOT NULL DEFAULT \'\''),
]


def _add_missing_columns(cursor, cols: set[str]) -> None:
    for name, frag in _EXTRA_COLUMNS:
        if name not in cols:
            cursor.execute(f'ALTER TABLE "{TABLE}" ADD COLUMN {frag};')
            cols.add(name)


def ensure_school_enrollment_storage() -> bool:
    """
    Ensure public.core_schoolenrollmentrequest exists and has columns for the current model.
    Returns True if no fatal error; logs and returns False on failure (non-PostgreSQL, etc.).
    """
    if not _is_postgres():
        logger.warning("Enrollment storage ensure skipped: database is not PostgreSQL.")
        return False

    try:
        connection.set_schema_to_public()
    except Exception:
        logger.exception("Could not switch to public schema for enrollment storage.")
        return False

    schema = _public_schema_name()

    try:
        with connection.cursor() as cursor:
            if not _table_exists(cursor, schema):
                logger.info("Creating %s.%s for school enrollment.", schema, TABLE)
                _create_table_and_constraints(cursor)
                return True

            cols = _existing_columns(cursor, schema)
            before = len(cols)
            _add_missing_columns(cursor, cols)
            if len(cols) > before:
                logger.info(
                    "Added %s missing column(s) on %s.%s.",
                    len(cols) - before,
                    schema,
                    TABLE,
                )
            return True
    except Exception:
        logger.exception("Enrollment storage ensure failed (DDL).")
        return False


def record_core_migrations_if_missing() -> None:
    """Optional: record core.0019 / 0020 in django_migrations when table was repaired manually."""
    if not _is_postgres():
        return
    try:
        connection.set_schema_to_public()
    except Exception:
        return
    names = ("0019_schoolenrollmentrequest", "0020_schoolenrollmentrequest_extended")
    try:
        with connection.cursor() as cursor:
            for name in names:
                cursor.execute(
                    "SELECT 1 FROM django_migrations WHERE app = 'core' AND name = %s;",
                    [name],
                )
                if cursor.fetchone():
                    continue
                cursor.execute(
                    "INSERT INTO django_migrations (app, name, applied) VALUES ('core', %s, NOW());",
                    [name],
                )
                logger.info("Recorded core.%s in django_migrations.", name)
    except Exception:
        logger.exception("Could not record enrollment migrations in django_migrations.")
