"""
Idempotent public-schema DDL for SidebarMenuItem when migrations are blocked/inconsistent.

Used by ensure_sidebar_menu_table management command.
"""

from __future__ import annotations

import logging

from django.db import connection

logger = logging.getLogger(__name__)

TABLE = "core_sidebarmenuitem"


def _public_schema_name() -> str:
    try:
        from django_tenants.utils import get_public_schema_name

        return get_public_schema_name()
    except Exception:
        return "public"


def _is_postgres() -> bool:
    engine = connection.settings_dict.get("ENGINE") or ""
    return "postgresql" in engine


def _table_exists(cursor, schema: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = %s AND table_name = %s
        """,
        [schema, TABLE],
    )
    return cursor.fetchone() is not None


def _create_table_and_constraints(cursor) -> None:
    cursor.execute(
        f'''
        CREATE TABLE "{TABLE}" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "created_on" timestamp with time zone NOT NULL,
            "modified_on" timestamp with time zone NOT NULL,
            "role" varchar(20) NOT NULL,
            "label" varchar(80) NOT NULL,
            "route_name" varchar(120) NOT NULL,
            "href" varchar(240) NOT NULL,
            "icon" varchar(60) NOT NULL,
            "display_order" integer NOT NULL,
            "is_visible" boolean NOT NULL,
            "is_active" boolean NOT NULL,
            "feature_code" varchar(64) NOT NULL,
            "created_by_id" bigint NULL,
            "modified_by_id" bigint NULL,
            "parent_id" bigint NULL
        );
        '''
    )
    cursor.execute(
        f'''
        ALTER TABLE "{TABLE}"
        ADD CONSTRAINT "core_sidebarmenuitem_created_by_id_fk_accounts_user"
        FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id")
        DEFERRABLE INITIALLY DEFERRED;
        '''
    )
    cursor.execute(
        f'''
        ALTER TABLE "{TABLE}"
        ADD CONSTRAINT "core_sidebarmenuitem_modified_by_id_fk_accounts_user"
        FOREIGN KEY ("modified_by_id") REFERENCES "accounts_user" ("id")
        DEFERRABLE INITIALLY DEFERRED;
        '''
    )
    cursor.execute(
        f'''
        ALTER TABLE "{TABLE}"
        ADD CONSTRAINT "core_sidebarmenuitem_parent_id_fk_core_sidebarmenuitem"
        FOREIGN KEY ("parent_id") REFERENCES "{TABLE}" ("id")
        DEFERRABLE INITIALLY DEFERRED;
        '''
    )
    for stmt in (
        f'CREATE INDEX "core_sidebarmenuitem_role_idx" ON "{TABLE}" ("role");',
        f'CREATE INDEX "core_sidebarmenuitem_role_parent_order_idx" ON "{TABLE}" ("role", "parent_id", "display_order");',
        f'CREATE INDEX "core_sidebarmenuitem_parent_id_idx" ON "{TABLE}" ("parent_id");',
        f'CREATE INDEX "core_sidebarmenuitem_created_on_idx" ON "{TABLE}" ("created_on");',
    ):
        cursor.execute(stmt)


def ensure_sidebar_menu_storage() -> bool:
    if not _is_postgres():
        logger.warning("Sidebar menu storage ensure skipped: database is not PostgreSQL.")
        return False
    try:
        connection.set_schema_to_public()
    except Exception:
        logger.exception("Could not switch to public schema for sidebar menu storage.")
        return False

    schema = _public_schema_name()
    try:
        with connection.cursor() as cursor:
            if _table_exists(cursor, schema):
                return True
            logger.info("Creating %s.%s for sidebar menu.", schema, TABLE)
            _create_table_and_constraints(cursor)
            return True
    except Exception:
        logger.exception("Sidebar menu storage ensure failed (DDL).")
        return False


def record_core_sidebar_migration_if_missing() -> None:
    """Optional: record core.0021_sidebar_menu_item in django_migrations when created manually."""
    if not _is_postgres():
        return
    try:
        connection.set_schema_to_public()
    except Exception:
        return
    name = "0021_sidebar_menu_item"
    try:
        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM django_migrations WHERE app = 'core' AND name = %s;",
                [name],
            )
            if cursor.fetchone():
                return
            cursor.execute(
                "INSERT INTO django_migrations (app, name, applied) VALUES ('core', %s, NOW());",
                [name],
            )
            logger.info("Recorded core.%s in django_migrations.", name)
    except Exception:
        logger.exception("Could not record core sidebar migration in django_migrations.")

