# Generated by Django 6.0.2 on 2026-03-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_data', '0008_add_test_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Basic'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='% or fixed amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['component_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_date', models.DateField()),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='school_data.teacher')),
            ],
            options={
                'ordering': ['-advance_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='school_data.teacher')),
            ],
            options={
                'ordering': ['teacher__user__first_name', 'teacher__user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('earnings_breakdown', models.JSONField(blank=True, default=dict)),
                ('deductions_breakdown', models.JSONField(blank=True, default=dict)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='Bank Transfer', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROCESSED', 'Processed'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='school_data.teacher')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
