# Generated by Django 6.0.2 on 2026-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payslip_payment_method_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='applicable_components',
            field=models.ManyToManyField(blank=True, help_text='Links when not using default list, plus optional per-employee rate overrides.', related_name='salary_structures', through='payroll.SalaryStructureComponent', to='payroll.salarycomponent'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='use_default_salary_components',
            field=models.BooleanField(default=True, help_text='If True, every active allowance and deduction applies. If False, only linked components apply.'),
        ),
    ]
