# Generated by Django 6.0.2 on 2026-03-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentNotificationRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_reads",
                        to="notifications.notificationlog",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_notifications",
                        to="school_data.student",
                    ),
                ),
            ],
            options={"ordering": ["-read_at"]},
        ),
        migrations.AddConstraint(
            model_name="studentnotificationread",
            constraint=models.UniqueConstraint(
                fields=("student", "notification"),
                name="unique_student_notification_read",
            ),
        ),
    ]

